[package]
name = "whats-changed"
version = "0.1.0"
description = "Show Rust dependencies that were upgraded"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
semver = "1.0"
tempfile = "3.24"
toml = "0.9"
walkdir = "2.5"
